# Add 'root' label to any root file changes
# Quotation marks are required for the leading asterisk
root:
- changed-files:
  - any-glob-to-any-file: '*'

# Add 'update' label to any changes within the entire repository
update:
- changed-files:
  - any-glob-to-any-file: '**'

# Add 'documentation' label to any changes within 'documentation' folder or any subfolders
documentation:
- changed-files:
  - any-glob-to-any-file: documentation/**

# Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
source:
- all:
  - changed-files:
    - any-glob-to-any-file: 'src/**/*'
    - all-globs-to-all-files: '!src/docs/*'


# Add 'release' label to any PR that is opened against the `main` branch
release:
 - base-branch: 'main'

# Add 'bug' label to any file where a bug is detected
bug: 
 - title: "bug"
 - body: "bug"
 - any-commits:
    - message: "fix bug"
    - message: "bug"

# Add 'security' label when the code is linked at a security level 
security: 
 - title: "security"
 - body: "security"
 - any-commits:
    - message: "security"
    - message: "security"

# Add 'creation' label when the file does not exist and has just been created 
creation:
  - all:
      - created-files:
          - any-glob-to-any-file: '**/*'

# Add 'question'
question: 
 - title: "question"
 - body: "question"
 - any-commits:
    - message: "question"
    - message: "question"

# Add 'help' 
help: 
 - title: "help"
 - body: "help"
 - any-commits:
    - message: "help"
    - message: "help"
