name: 🚀 Feature request
description: Suggest an idea for this project
title: "[FEATURE] Short description of the feature"
labels: [feature request]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an idea to make this 2048 project better.🎉

        Please fill in as much of the following form as you are able.
  - type: textarea
    attributes:
      label: ⁉️ What is the problem this feature will solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🆕 What is the feature you are proposing to solve the problem?
    validations:
      required: true
  - type: textarea
    attributes:
      label: ❕ What alternatives have you considered?
