on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  check-results:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch check runs
        uses: actions/github-script@v6
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const prNumber = context.payload.pull_request.number;

            // Fetch all checks for this pull request
            const { data: checkRuns } = await github.rest.checks.listForRef({
              owner,
              repo,
              ref: context.payload.pull_request.head.sha,
            });

            // Check if any of the checks failed
            const failedCheck = checkRuns.check_runs.some(run => run.conclusion === "failure");

            if (failedCheck) {
              console.log(`Some checks failed for PR #${prNumber}. Adding "invalid" label.`);

              // Add the "invalid" label to the PR
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: prNumber,
                labels: ["invalid"],
              });
            } else {
              console.log(`All checks passed for PR #${prNumber}. No label added.`);
            }
