name: Apply "invalid" label for failed checks

on:
  check_suite:
    types: [completed]

jobs:
  label-invalid:
    runs-on: ubuntu-latest

    steps:
    - name: Check if checks failed
      uses: actions/github-script@v6
      with:
        script: |
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const checkSuite = context.payload.check_suite;

          // Only process pull requests
          const pullRequest = checkSuite.pull_requests[0];
          if (!pullRequest) {
            console.log("No pull request found. Skipping...");
            return;
          }

          const prNumber = pullRequest.number;

          // Fetch all checks for this pull request
          const { data: checkRuns } = await github.rest.checks.listForSuite({
            owner,
            repo,
            check_suite_id: checkSuite.id,
          });

          // Check if any of the checks failed
          const failedCheck = checkRuns.check_runs.some(run => run.conclusion === "failure");

          if (failedCheck) {
            console.log(`Some checks failed for PR #${prNumber}. Adding "invalid" label.`);

            // Add the "invalid" label to the PR
            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: prNumber,
              labels: ["invalid"],
            });
          } else {
            console.log(`All checks passed for PR #${prNumber}. No label added.`);
          }
